{% set name = "flake8-eradicate" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aee636cb9ecb5594a7cd92d67ad73eb69909e5cc7bd81710cf9d00970f3983a6

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.6.0
    - python {{ python_min }}
  run:
    - attrs
    - eradicate >=2.0,<3.0
    - flake8 >5
    - python >={{ python_min }},<4.0

test:
  imports:
    - flake8_eradicate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sobolevn/flake8-eradicate
  summary: Flake8 plugin to find commented out code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
