{% set name = "flake8-eradicate" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-eradicate-{{ version }}.tar.gz
  sha256: e486f8ab7e2dba3667223688e9239158fbf4ecaa88125e2283bcda81171412b7

build:
  number: 0
  noarch: python
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - attrs
    - eradicate >=2.0,<3.0
    - flake8 >=3.5,<4.0
    - python >=3.6,<4.0

test:
  imports:
    - flake8_eradicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sobolevn/flake8-eradicate
  summary: Flake8 plugin to find commented out code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
